g2forge/gearbox

- gb-functional/src/main/java/com/g2forge/gearbox/functional/control/Command.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/control/Constant.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/control/Explicit.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/control/IArgumentContext.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/control/ICommandBuilder.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/control/IExplicitArgumentHandler.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/control/IExplicitResultHandler.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/control/IResultContext.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/control/Named.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/proxy/ArgumentContext.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/proxy/CommandBuilder.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/proxy/ProxyInvocationHandler.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/proxy/ResultContext.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/runner/Command.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/runner/IProcess.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/runner/IStandardIO.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/runner/ProcessBuilderRunner.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/runner/redirect/FileRedirect.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/runner/redirect/IRedirect.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/runner/redirect/InheritRedirect.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/runner/redirect/PipeRedirect.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/runner/redirect/Redirects.java
- gb-functional/src/test/java/com/g2forge/gearbox/functional/TestProxifier.java
- gb-git-test/.gitignore
- gb-git-test/pom.xml
- gb-git-test/src/main/java/com/g2forge/gearbox/git/TempGitRepository.java
- gb-git/.gitignore
- gb-git/pom.xml
- gb-git/src/main/java/com/g2forge/gearbox/git/HGit.java
- gb-jira/src/test/java/com/g2forge/gearbox/jira/TestJIRAServer.java
Depends on https://github.com/g2forge/alexandria/pull/135
> G2-185 Release, functional improvements, git, logging cleanup

- .gitignore
- gb-functional/pom.xml
- gb-functional/src/main/java/com/g2forge/gearbox/functional/proxy/ResultContext.java
- gb-git-test/src/main/java/com/g2forge/gearbox/git/TempGitRepository.java
- gb-git-test/src/test/java/com/g2forge/gearbox/git/TestHGit.java
- gb-git/src/main/java/com/g2forge/gearbox/git/GitConfig.java
- gb-git/src/main/java/com/g2forge/gearbox/git/GitRemote.java
- gb-git/src/main/java/com/g2forge/gearbox/git/HGit.java
- gb-git/src/main/java/com/g2forge/gearbox/git/HSSH.java
- gb-git/src/main/java/com/g2forge/gearbox/git/IGitConfigAccessor.java
- gb-git/src/main/java/com/g2forge/gearbox/git/ssh/PasswordSSHUserInfo.java
- gb-github/.gitignore
- gb-github/pom.xml
- pom.xml
Depends on https://github.com/g2forge/alexandria/pull/136
> G2-106 Automate catalog of G2Forge projects

- gb-functional/pom.xml
- gb-git-test/pom.xml
- gb-git/pom.xml
- gb-github/pom.xml
- gb-jira/pom.xml
- gb-project/pom.xml
- pom.xml
Depends on https://github.com/g2forge/alexandria/pull/138
> G2-193 Release Bulldozer

- gb-git/src/main/java/com/g2forge/gearbox/git/GitIgnore.java
- gb-git/src/main/java/com/g2forge/gearbox/git/GitRemote.java
Depends on https://github.com/g2forge/alexandria/pull/139
> G2-207 Automate CreateProject using bulldozer

- gb-functional-test/pom.xml
Depends on https://github.com/g2forge/alexandria/pull/146
> G2-308 Abstract & Memory FileSystem Provider

- gb-browser/.gitignore
- gb-browser/pom.xml
- gb-browser/src/main/java/com/g2forge/gearbox/browser/IBrowsable.java
- gb-browser/src/main/java/com/g2forge/gearbox/browser/IBrowser.java
- gb-browser/src/main/java/com/g2forge/gearbox/browser/IElement.java
- gb-browser/src/main/java/com/g2forge/gearbox/browser/IForm.java
- gb-browser/src/main/java/com/g2forge/gearbox/browser/StatefulBrowser.java
- gb-browser/src/main/java/com/g2forge/gearbox/browser/operation/ChangeWait.java
- gb-browser/src/main/java/com/g2forge/gearbox/browser/operation/IOperationBuilder.java
- gb-browser/src/main/java/com/g2forge/gearbox/browser/operation/IOperationWrapper.java
- gb-browser/src/main/java/com/g2forge/gearbox/browser/operation/LoadWait.java
- gb-browser/src/main/java/com/g2forge/gearbox/browser/operation/WrappedOperationBuilder.java
- gb-browser/src/main/java/com/g2forge/gearbox/browser/selenium/Element.java
- gb-browser/src/main/java/com/g2forge/gearbox/browser/selenium/Form.java
- gb-browser/src/main/java/com/g2forge/gearbox/browser/selenium/SeleniumBrowser.java
- gb-browser/src/test/java/com/g2forge/gearbox/browser/TestBrowser.java
- gb-browser/src/test/java/com/g2forge/gearbox/browser/example/ExampleHome.java
- gb-browser/src/test/java/com/g2forge/gearbox/browser/example/ExampleMoreInformation.java
- gb-browser/src/test/java/com/g2forge/gearbox/browser/example/ExampleSite.java
- gb-browser/src/test/java/com/g2forge/gearbox/browser/example/TestExample.java
- pom.xml
Depends on https://github.com/g2forge/alexandria/pull/149
> G2-328 Gearbox Browser (Web Client)

- gb-functional/src/main/java/com/g2forge/gearbox/functional/control/ModifyCommandException.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/control/TypedInvocation.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/proxy/ProxyInvocationHandler.java
- lombok.config
Depends on https://github.com/g2forge/alexandria/pull/159
> G2-407 Lombok config

- gb-browser/src/main/java/com/g2forge/gearbox/browser/operation/ChangeWait.java
- gb-browser/src/main/java/com/g2forge/gearbox/browser/operation/LoadWait.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/runner/redirect/InheritRedirect.java
- gb-functional/src/main/java/com/g2forge/gearbox/functional/runner/redirect/PipeRedirect.java
- gb-git-test/src/main/java/com/g2forge/gearbox/git/TempGitRepository.java
- gb-git/src/main/java/com/g2forge/gearbox/git/HGit.java
- gb-git/src/main/java/com/g2forge/gearbox/git/HSSH.java
Depends on https://github.com/g2forge/alexandria/pull/160
> G2-428 Alexandria core cleanup

- gb-browser/src/main/java/com/g2forge/gearbox/browser/by/ByText.java
- gb-functional/pom.xml
Depends on https://github.com/g2forge/alexandria/pull/163
> G2-430 ADTs

- gb-ssh/.gitignore
Depends on https://github.com/g2forge/alexandria/pull/169
> G2-341 Simplify Install

- gb-command-test/src/test/java/com/g2forge/gearbox/command/test/TestCommand.java
- gb-command/src/main/java/com/g2forge/gearbox/command/converter/manual/v1/IArgumentConsumer.java
- gb-command/src/main/java/com/g2forge/gearbox/command/converter/manual/v1/IMethodConsumer.java
- gb-command/src/main/java/com/g2forge/gearbox/command/proxy/ProxyInvocationHandler.java
- gb-command/src/test/java/com/g2forge/gearbox/command/converter/dumb/TestDumbCommandConverter.java
- gb-command/src/test/java/com/g2forge/gearbox/command/converter/manual/v1/TestMethodToCommandInvocationTransformer.java
- gb-command/src/test/java/com/g2forge/gearbox/command/proxy/TestCommandProxyFactory.java
- gb-command/src/test/java/com/g2forge/gearbox/command/proxy/TestProxyInvocationHandler.java
- gb-command/src/test/java/com/g2forge/gearbox/command/proxy/method/ITestCommandInterface.java
- gb-command/src/test/java/com/g2forge/gearbox/command/proxy/transformers/CustomInvocationTransformer.java
- gb-command/src/test/java/com/g2forge/gearbox/command/proxy/transformers/TestDefaultMethodInvocationTransformer.java
- gb-command/src/test/java/com/g2forge/gearbox/command/proxy/transformers/TestMetadataDispatchInvocationTransformer.java
Depends on https://github.com/g2forge/alexandria/pull/173
> G2-312 Pre-release fixes

- .gitignore
- gb-browser/pom.xml
- gb-command-test/pom.xml
- gb-command/pom.xml
- gb-git-test/pom.xml
- gb-git/pom.xml
- gb-github/pom.xml
- gb-jira/pom.xml
- gb-project/.gitignore
- gb-project/pom.xml
- gb-ssh/pom.xml
- pom.xml
Depends on https://github.com/g2forge/alexandria/pull/179
> G2-312 Alexandria 0.0.8 & Gearbox 0.0.3 Release

- gb-git-test/src/main/java/com/g2forge/gearbox/git/TempGitRepository.java
Depends on https://github.com/g2forge/alexandria/pull/183
> G2-495 ICloseableSupplier

- gb-command/src/main/java/com/g2forge/gearbox/command/converter/ICommandConverter__.java
- gb-command/src/main/java/com/g2forge/gearbox/command/converter/dumb/DumbCommandConverter.java
- gb-ssh/src/main/java/com/g2forge/gearbox/ssh/SSHRunner.java
Depends on https://github.com/g2forge/alexandria/pull/191
> G2-524 Use @Note

- gb-project/pom.xml
Depends on https://github.com/g2forge/alexandria/pull/200
> G2-618 Released Alexandria & Engima

- gb-browser/pom.xml
- gb-command-test/pom.xml
- gb-command/pom.xml
- gb-git-test/pom.xml
- gb-git/pom.xml
- gb-github/pom.xml
- gb-jira/pom.xml
- gb-project/pom.xml
- gb-ssh/pom.xml
- pom.xml
Depends on https://github.com/g2forge/alexandria/pull/222
> G2-678 Release Alexandria, Enigma & Gearbox

- gb-command/pom.xml
- gb-command/src/main/java/com/g2forge/gearbox/command/converter/ICommandConverterR_.java
- gb-command/src/main/java/com/g2forge/gearbox/command/converter/ICommandConverter__.java
- gb-command/src/main/java/com/g2forge/gearbox/command/converter/IMethodArgument.java
- gb-command/src/main/java/com/g2forge/gearbox/command/converter/MethodArgument.java
- gb-command/src/main/java/com/g2forge/gearbox/command/converter/dumb/DumbCommandConverter.java
- gb-command/src/main/java/com/g2forge/gearbox/command/converter/dumb/IArgumentRenderer.java
- gb-command/src/main/java/com/g2forge/gearbox/command/converter/manual/v1/IArgumentConsumer.java
- gb-command/src/main/java/com/g2forge/gearbox/command/converter/manual/v1/IMethodConsumer.java
- gb-command/src/main/java/com/g2forge/gearbox/command/converter/manual/v1/MethodToCommandInvocationTransformer.java
- gb-command/src/main/java/com/g2forge/gearbox/command/proxy/transformers/MetadataDispatchInvocationTransformer.java
- gb-command/src/main/java/com/g2forge/gearbox/command/proxy/transformers/MethodToCommandInvocationTransformer.java
- gb-project/pom.xml
Depends on https://github.com/g2forge/habitat/pull/17
> G2-589 Habitat metadata

- gb-browser/pom.xml
- gb-command-test/pom.xml
- gb-command/pom.xml
- gb-git-test/pom.xml
- gb-git/pom.xml
- gb-github/pom.xml
- gb-jira/pom.xml
- gb-project/pom.xml
- gb-ssh/pom.xml
- pom.xml
Depends on https://github.com/g2forge/alexandria/pull/226, https://github.com/g2forge/habitat/pull/19
> G2-703 Release Alexandria, Habitat, Enigma & Gearbox

- gb-command-test/src/main/java/com/g2forge/gearbox/command/test/ATestCommand.java
- gb-ssh/src/test/java/com/g2forge/gearbox/ssh/TestSSHRunner.java
Depends on https://github.com/g2forge/alexandria/pull/228
> G2-713 Ignore SSH tests when server properties are unspecified

- gb-command-test/src/test/java/com/g2forge/gearbox/command/test/TestCommand.java
Depends on https://github.com/g2forge/alexandria/pull/231
> G2-750 Unify alexandria & enigma quoting

- .github/workflows/maven.yml
- gb-github/pom.xml
- gb-github/src/main/java/com/g2forge/gearbox/github/actions/GHActionEvent.java
- gb-github/src/main/java/com/g2forge/gearbox/github/actions/GHActionEventConfiguration.java
- gb-github/src/main/java/com/g2forge/gearbox/github/actions/GHActionEventType.java
- gb-github/src/main/java/com/g2forge/gearbox/github/actions/GHActionJob.java
- gb-github/src/main/java/com/g2forge/gearbox/github/actions/GHActionStep.java
- gb-github/src/main/java/com/g2forge/gearbox/github/actions/GHActionWorkflow.java
- gb-github/src/main/java/com/g2forge/gearbox/github/actions/HGHActions.java
- gb-github/src/test/java/com/g2forge/gearbox/github/actions/TestGHAction.java
- gb-github/src/test/java/com/g2forge/gearbox/github/actions/maven.yaml
Depends on https://github.com/g2forge/alexandria/pull/239, https://github.com/g2forge/habitat/pull/23
> G2-791 Setup GH actions for existing & new repos

- gb-git/pom.xml
- gb-github/src/test/java/com/g2forge/gearbox/github/actions/maven.yaml
Depends on https://github.com/g2forge/alexandria/pull/251
> G2-853 Minor updates

- gb-command/src/main/java/com/g2forge/gearbox/command/process/IProcess.java
- gb-command/src/main/java/com/g2forge/gearbox/command/proxy/result/StreamResultSupplier.java
- gb-command/src/main/java/com/g2forge/gearbox/command/proxy/result/StringResultSupplier.java
Depends on https://github.com/g2forge/alexandria/pull/253
> G2-813 Create HTextIO with isEqual

- .github/workflows/maven.yml
- gb-browser/src/main/java/com/g2forge/gearbox/browser/selenium/SeleniumBrowser.java
- gb-browser/src/test/java/com/g2forge/gearbox/browser/TestBrowser.java
- gb-browser/src/test/java/com/g2forge/gearbox/browser/example/TestExample.java
- gb-command/src/test/java/com/g2forge/gearbox/command/proxy/transformers/TestDefaultMethodInvocationTransformer.java
- gb-github/src/main/java/com/g2forge/gearbox/github/actions/GHActionStep.java
- gb-github/src/main/java/com/g2forge/gearbox/github/actions/HGHActions.java
- gb-github/src/test/java/com/g2forge/gearbox/github/actions/TestGHAction.java
- gb-github/src/test/java/com/g2forge/gearbox/github/actions/maven.yaml
Depends on https://github.com/g2forge/alexandria/pull/240, https://github.com/g2forge/habitat/pull/24
> G2-791 Added upstream builds to GH actions workflow

- gb-browser/pom.xml
- gb-command-test/pom.xml
- gb-command/pom.xml
- gb-git-test/pom.xml
- gb-git/pom.xml
- gb-github/pom.xml
- gb-jira/pom.xml
- gb-project/pom.xml
- gb-ssh/pom.xml
- pom.xml
Depends on https://github.com/g2forge/alexandria/pull/262, https://github.com/g2forge/habitat/pull/26
> G2-756 Public release

- gb-jira/src/main/java/com/g2forge/gearbox/jira/createissues/CreateIssues.java
Depends on https://github.com/g2forge/alexandria/pull/272, https://github.com/g2forge/habitat/pull/27
> G2-936 Cleanup error helpers

- gb-project/pom.xml
Depends on https://github.com/g2forge/alexandria/pull/279, https://github.com/g2forge/habitat/pull/28
> G2-955 Release preparations

- gb-browser/pom.xml
- gb-command-test/pom.xml
- gb-command/pom.xml
- gb-git-test/pom.xml
- gb-git/pom.xml
- gb-github/pom.xml
- gb-jira/pom.xml
- gb-project/pom.xml
- gb-ssh/pom.xml
- pom.xml
Depends on https://github.com/g2forge/alexandria/pull/280, https://github.com/g2forge/habitat/pull/29
> G2-955 Release

- gb-jira/src/main/java/com/g2forge/gearbox/jira/createissues/CreateIssues.java
Depends on https://github.com/g2forge/alexandria/pull/284
> G2-965 DispatchCommand & command naming

- .github/workflows/maven.yml
- gb-command-test/src/main/java/com/g2forge/gearbox/command/test/ATestCommand.java
- gb-command/src/main/java/com/g2forge/gearbox/command/converter/ICommandConverter__.java
- gb-command/src/main/java/com/g2forge/gearbox/command/converter/dumb/IArgumentRenderer.java
- gb-command/src/main/java/com/g2forge/gearbox/command/converter/manual/v1/IArgumentConsumer.java
- gb-command/src/main/java/com/g2forge/gearbox/command/converter/manual/v1/IMethodConsumer.java
- gb-command/src/main/java/com/g2forge/gearbox/command/process/IProcess.java
- gb-command/src/main/java/com/g2forge/gearbox/command/process/ProcessBuilderRunner.java
- gb-command/src/main/java/com/g2forge/gearbox/command/proxy/result/StreamConsumer.java
- gb-command/src/main/java/com/g2forge/gearbox/command/proxy/result/StreamResultSupplier.java
- gb-command/src/main/java/com/g2forge/gearbox/command/proxy/transformers/MetadataDispatchInvocationTransformer.java
- gb-github/src/main/java/com/g2forge/gearbox/github/actions/HGHActions.java
- gb-github/src/test/java/com/g2forge/gearbox/github/actions/maven.yaml
- gb-maven/.gitignore
- gb-maven/pom.xml
- gb-maven/src/main/java/com/g2forge/gearbox/maven/HMaven.java
- gb-maven/src/main/java/com/g2forge/gearbox/maven/IMaven.java
- gb-maven/src/main/java/com/g2forge/gearbox/maven/MavenCoordinates.java
- gb-maven/src/main/java/com/g2forge/gearbox/maven/MavenDownloadErrors.java
- gb-maven/src/main/java/com/g2forge/gearbox/maven/MavenPackaging.java
- gb-maven/src/main/java/com/g2forge/gearbox/maven/ProcessOutputHandler.java
- gb-ssh/src/main/java/com/g2forge/gearbox/ssh/SSHRunner.java
- pom.xml
Depends on https://github.com/g2forge/alexandria/pull/296
> G2-1148 gb-maven, Java11 & thread actors

- gb-browser/pom.xml
- gb-cli/pom.xml
- gb-command-test/pom.xml
- gb-command/pom.xml
- gb-git-test/pom.xml
- gb-git/pom.xml
- gb-github/pom.xml
- gb-image/pom.xml
- gb-jira/pom.xml
- gb-maven/pom.xml
- gb-project/pom.xml
- gb-rest/pom.xml
- gb-ssh/pom.xml
- pom.xml
Depends on https://github.com/g2forge/enigma/pull/96, https://github.com/g2forge/alexandria/pull/312, https://github.com/g2forge/habitat/pull/34
> G2-1163 Release Joint & public projects

- gb-browser/pom.xml
- gb-cli/pom.xml
- gb-command-test/pom.xml
- gb-command/pom.xml
- gb-git-test/pom.xml
- gb-git/pom.xml
- gb-github/pom.xml
- gb-image/pom.xml
- gb-jira/pom.xml
- gb-maven/pom.xml
- gb-project/pom.xml
- gb-rest/pom.xml
- gb-ssh/pom.xml
- pom.xml
Depends on https://github.com/g2forge/enigma/pull/98, https://github.com/g2forge/alexandria/pull/316, https://github.com/g2forge/habitat/pull/36
> G2-1190 Release Joint 0.0.2 & Upstreams

- gb-jira/pom.xml
- gb-jira/src/main/java/com/g2forge/gearbox/jira/AsynchronousProjectComponentClient.java
- gb-jira/src/main/java/com/g2forge/gearbox/jira/BasicComponentsJsonParser.java
- gb-jira/src/main/java/com/g2forge/gearbox/jira/ExtendedAsynchronousJiraRestClient.java
- gb-jira/src/main/java/com/g2forge/gearbox/jira/ExtendedJiraRestClient.java
- gb-jira/src/main/java/com/g2forge/gearbox/jira/JIRAServer.java
- gb-jira/src/main/java/com/g2forge/gearbox/jira/ProjectComponentsRestClient.java
- gb-jira/src/main/java/com/g2forge/gearbox/jira/createissues/CreateConfig.java
- gb-jira/src/main/java/com/g2forge/gearbox/jira/createissues/CreateIssue.java
- gb-jira/src/main/java/com/g2forge/gearbox/jira/createissues/CreateIssues.java
- gb-jira/src/main/java/com/g2forge/gearbox/jira/createissues/ICreateConfig.java
> G2-1376 Add CreateIssues support for components & upgrade jira dependencies

- gb-command/pom.xml
- gb-maven/pom.xml
Depends on https://github.com/g2forge/alexandria/pull/353
> G2-1477 Remove unnecessary dependency; replace with proper dependency

- .github/workflows/maven.yml
- gb-jira/pom.xml
Depends on https://github.com/g2forge/alexandria/pull/355
> G2-1483 Upgrade to Java17

- gb-ssh/src/main/java/com/g2forge/gearbox/ssh/SSHConfig.java
- gb-ssh/src/main/java/com/g2forge/gearbox/ssh/SSHRunner.java
Depends on https://github.com/g2forge/gearbox/pull/120
> G2-1545 Support shared SSH client in SFTP filesystems

- gb-ssh/src/main/java/com/g2forge/gearbox/ssh/SSHConfig.java
- gb-ssh/src/main/java/com/g2forge/gearbox/ssh/SSHRunner.java
- gb-ssh/src/test/java/com/g2forge/gearbox/ssh/TestSSH.java
- gb-ssh/src/test/java/com/g2forge/gearbox/ssh/TestSSHProxy.java
- gb-ssh/src/test/java/com/g2forge/gearbox/ssh/TestSSHRunner.java
Depends on https://github.com/g2forge/gearbox/pull/121
> G2-1546 Test SSH w/port forwarding  @gdgib gdgib committed 2 minutes ago

- gb-command/src/main/java/com/g2forge/gearbox/command/proxy/result/StreamResultSupplier.java
Depends on https://github.com/g2forge/alexandria/pull/374
> G2-1644 Create ax-path module & sketch API

- .github/workflows/maven.yml
- gb-command-test/.gitignore
- gb-command-test/src/main/java/com/g2forge/gearbox/command/test/ATestCommand.java
- gb-command-test/src/test/java/com/g2forge/gearbox/command/test/TestPath.java
- gb-command/src/test/java/com/g2forge/gearbox/command/TestHelloWorld.java
Depends on https://github.com/g2forge/alexandria/pull/393
> Verify cross-platform support for CommandInvocation overrides of PATH using CLIReport

- gb-command-test/src/test/java/com/g2forge/gearbox/command/test/TestExitCode.java
Depends on https://github.com/g2forge/alexandria/pull/404
> G2-1747 Force & log exit codes

- gb-rest/src/main/java/com/g2forge/gearbox/rest/HReST.java
- gb-rest/src/main/java/com/g2forge/gearbox/rest/UnsafeOkHttpClient.java
Depends on https://github.com/g2forge/alexandria/pull/406
> G2-1752 Share unsafe SSL classes
